from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('medicines/', views.substitute_view, name='medicines'),
    path('fundraise/', views.fundraise_view, name='fundraise'),
    path('diagnose/', views.diagnose_view, name='diagnose'),
    path('tracker/', views.health_tracker_view, name='health_tracker'),
    path('schemes/', views.government_scheme_view, name='schemes'),
    path('appointment/', views.appointment_list, name='appointment_list'), # New appointment list view
    path('appointments/create/', views.create_appointment, name='create_appointment'),
    path('appointments/<int:pk>/', views.appointment_detail, name='appointment_detail'),
    path('appointments/<int:pk>/update_status/', views.update_appointment_status, name='update_appointment_status'),
    path('appointments/<int:pk>/cancel/', views.cancel_appointment, name='cancel_appointment'),
    path('contact/', views.contact_view, name='contact'),
    path('about/', views.about_us_view, name='about_us'),
    path('privacy/', views.privacy_policy_view, name='privacy_policy'),
    path('terms/', views.terms_of_service_view, name='terms_of_service'),
    path('login/', views.login_view, name='login'),
    path('eih/', views.eih_view, name='eih'),
    path('call/', views.create_room_view, name='create_room'),
    path('call/<uuid:room_id>/', views.call_view, name='call_page'),
    path('signaling/<uuid:room_id>/', views.signaling_view, name='signaling'),
    path('consultation/', views.consultation_view, name='consultation'),
    path('symptoms/', views.symptom_checker_view, name='symptom_checker'),
    path('prescription/create/', views.create_prescription_view, name='create_prescription'),
    path('tracker/update_dosage/', views.update_dosage_log_view, name='update_dosage_log'),

    path('health_tracker/add_weight/', views.add_weight, name='add_weight'),
    path('health_tracker/delete_weight/<int:pk>/', views.delete_weight, name='delete_weight'),
    path('health_tracker/add_blood_pressure/', views.add_blood_pressure, name='add_blood_pressure'),
    path('health_tracker/delete_blood_pressure/<int:pk>/', views.delete_blood_pressure, name='delete_blood_pressure'),
    path('health_tracker/add_glucose/', views.add_glucose, name='add_glucose'),
    path('health_tracker/delete_glucose/<int:pk>/', views.delete_glucose, name='delete_glucose'),
    path('health_tracker/set_weight_goal/', views.set_weight_goal, name='set_weight_goal'),
    path('health_tracker/set_blood_pressure_goal/', views.set_blood_pressure_goal, name='set_blood_pressure_goal'),
    path('health_tracker/set_glucose_goal/', views.set_glucose_goal, name='set_glucose_goal'),
    path('health_tracker/add_activity/', views.add_activity, name='add_activity'),
    path('health_tracker/delete_activity/<int:pk>/', views.delete_activity, name='delete_activity'),
    path('health_tracker/add_meal/', views.add_meal, name='add_meal'),
    path('health_tracker/delete_meal/<int:pk>/', views.delete_meal, name='delete_meal'),
    path('health_tracker/update_height/', views.update_height, name='update_height'),
    path('health_tracker/export_csv/', views.export_health_data_csv, name='export_health_data_csv'),
]
