# Generated by Django 5.2.8 on 2025-12-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bloodpressureentry_glucoseentry_weightentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_systolic', models.IntegerField()),
                ('target_diastolic', models.IntegerField()),
                ('set_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_date'],
                'unique_together': {('user', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='GlucoseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_glucose_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('set_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_date'],
                'unique_together': {('user', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='WeightGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('set_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_date'],
                'unique_together': {('user', 'is_active')},
            },
        ),
    ]
